server:
  port: 31001
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    sentinel:
      nodes: 127.0.0.1:26379,127.0.0.1:26389,127.0.0.1:26399
      master: mymaster
    database: 0
    password: pass1234
    timeout: 10000ms
    jedis:
      pool:
        max-wait: 10000ms
        max-active: 50
        max-idle: 50
        min-idle: 1


